"""Test battery for the Biot-Savart package. No repository or shot data needed.

    python -m methods_script.biot_savart.tests

T1  on-axis field against the elementary closed form   (external reference)
T2  div B = 0 and curl B = 0 off the wire              (external constraint)
T3  mirror symmetry about the loop plane
T4  recovery error against injected noise (synthetic signals)
T5  invariance of the fit to overall signal scaling
T6  trajectory tracking with the grid search
T7  behaviour on dead probes, NaNs, the Ip gate and probe subsets
"""

from __future__ import annotations

import warnings

import numpy as np

warnings.filterwarnings("ignore")

from . import adapter, field, invert  # noqa: E402

MU0 = 4.0e-7 * np.pi
GEOM = adapter.load_geometry(strict=False)
FWD = adapter.load_forward("internal", GEOM)
FWD_MANY = adapter.load_forward_many(GEOM)
TPL = invert.Templates(FWD_MANY, np.arange(12), np.ones(12), step=0.002)

_results = []


def _report(name, ok, detail):
    _results.append((name, ok))
    print(f"  [{'PASS' if ok else 'FAIL'}] {name}: {detail}")


# --------------------------------------------------------------------------


def t1_on_axis():
    """On the loop axis, Bz = mu0 I a^2 / (2 (a^2 + z^2)^{3/2}).

    No elliptic integrals appear, so this is a reference independent of
    field.py's formula, sensitive to the modulus-vs-parameter argument of
    ellipk/ellipe, to mu0 and to a factor of 2pi.
    """
    print("\nT1  on-axis field vs closed form (external reference)")
    a, I = 0.65, 1234.0
    z = np.array([0.0, 0.05, 0.2, 0.5, 1.0])
    eps = 1e-7                       # Br ~ 1/R, so approach the axis, not reach it
    _, Bz = field.loop_field(a, eps, z, I=I)
    exact = MU0 * I * a ** 2 / (2.0 * (a ** 2 + z ** 2) ** 1.5)
    rel = np.max(np.abs(Bz / exact - 1.0))
    _report("T1 on-axis", rel < 1e-6, f"max relative error {rel:.3e}")

    # Far field must approach a dipole of moment m = I * pi * a^2.
    zf = np.array([50.0, 200.0]) * a
    _, Bzf = field.loop_field(a, eps, zf, I=I)
    dip = MU0 * (I * np.pi * a ** 2) / (2.0 * np.pi * zf ** 3)
    relf = np.max(np.abs(Bzf / dip - 1.0))
    _report("T1 far-field dipole", relf < 1e-3, f"max relative error {relf:.3e}")


def t2_maxwell():
    """Off the wire, in cylindrical coordinates,

        div B  = (1/R) d(R Br)/dR + dBz/dz = 0
        curl B = dBr/dz - dBz/dR           = 0

    Evaluated by central differences. A wrong sign inside the elliptic-integral
    bracket breaks curl B while leaving the field finite and plausible.
    """
    print("\nT2  Maxwell constraints off the wire (external constraint)")
    a, I, h = 0.65, 1e4, 1e-5
    R = np.array([0.40, 0.55, 0.80, 0.95])
    Z = np.array([0.10, -0.15, 0.25, 0.05])
    Rg, Zg = np.meshgrid(R, Z)

    def B(r, z):
        return field.loop_field(a, r, z, I=I)

    Brp, Bzp = B(Rg + h, Zg)
    Brm, Bzm = B(Rg - h, Zg)
    Brzp, Bzzp = B(Rg, Zg + h)
    Brzm, Bzzm = B(Rg, Zg - h)
    Br0, Bz0 = B(Rg, Zg)

    d_rBr_dR = ((Rg + h) * Brp - (Rg - h) * Brm) / (2 * h)
    dBz_dz = (Bzzp - Bzzm) / (2 * h)
    div = d_rBr_dR / Rg + dBz_dz

    dBr_dz = (Brzp - Brzm) / (2 * h)
    dBz_dR = (Bzp - Bzm) / (2 * h)
    curl = dBr_dz - dBz_dR

    scale = np.max(np.abs([Br0, Bz0])) / min(R.min(), 0.1)
    _report("T2 div B = 0", np.max(np.abs(div)) / scale < 1e-6,
            f"max |div B| / scale = {np.max(np.abs(div)) / scale:.3e}")
    _report("T2 curl B = 0", np.max(np.abs(curl)) / scale < 1e-6,
            f"max |curl B| / scale = {np.max(np.abs(curl)) / scale:.3e}")


def t3_symmetry():
    """A loop in the plane z = 0 is mirror-symmetric about it: Bz is even in z,
    Br is odd. Sensitive to a sign slip in the vertical-separation convention.
    """
    print("\nT3  mirror symmetry about the loop plane")
    a, I = 0.65, 1e4
    R = np.array([0.45, 0.60, 0.90])
    z = np.array([0.03, 0.12, 0.3])
    Rg, Zg = np.meshgrid(R, z)
    Brp, Bzp = field.loop_field(a, Rg, Zg, I=I)
    Brm, Bzm = field.loop_field(a, Rg, -Zg, I=I)
    s = np.max(np.abs(Bzp))
    e_even = np.max(np.abs(Bzp - Bzm)) / s
    e_odd = np.max(np.abs(Brp + Brm)) / s
    _report("T3 Bz even in z", e_even < 1e-12, f"max deviation {e_even:.3e}")
    _report("T3 Br odd in z", e_odd < 1e-12, f"max deviation {e_odd:.3e}")


def t4_noise_budget(seed=1):
    """Recovery error against injected noise, over a grid of true positions.

    The signals are synthetic: generated by field.py at a known (dR, dZ), then
    perturbed by a gaussian of the stated fraction of the median |B|. Generator
    and inverter share field.py, so this measures the solver's sensitivity to a
    perturbation, not the accuracy of the field model and not anything about a
    real shot.
    """
    print("\nT4  injected noise -> error budget, synthetic (12 probes, cold start)")
    rng = np.random.default_rng(seed)
    truth = [(r * np.cos(p), r * np.sin(p))
             for r in (0.02, 0.06, 0.10, 0.14)
             for p in np.linspace(0, 2 * np.pi, 8, endpoint=False)]
    sq = np.ones(GEOM.angles.size)
    print("  injected   median err    p95 err     max err")
    prev = -1.0
    mono = True
    for frac in (0.001, 0.003, 0.01, 0.03, 0.10):
        errs = []
        for dR, dZ in truth:
            clean = FWD(dR, dZ)
            s = float(np.median(np.abs(clean)))
            meas = clean + rng.normal(0.0, frac * s, clean.size)
            x, *_ = invert.invert_sample(FWD, FWD_MANY, meas, sq, s, templates=TPL)
            errs.append(1e3 * np.hypot(x[0] - dR, x[1] - dZ))
        errs = np.array(errs)
        med = np.median(errs)
        print(f"    {frac:6.1%}  {med:10.2f} mm {np.percentile(errs, 95):8.2f} mm"
              f" {errs.max():8.2f} mm")
        mono &= med >= prev
        prev = med
    _report("T4 error grows monotonically with injected noise", mono,
            "no inversion in the sequence")


def t5_amplitude_invariance(seed=2):
    """With the amplitude profiled out, scaling every probe signal by a constant
    must leave (dR, dZ) unchanged and scale the reported amplitude by exactly
    that constant.
    """
    print("\nT5  amplitude invariance (the profiling decision)")
    sq = np.ones(GEOM.angles.size)
    dR, dZ = 0.07, -0.04
    clean = FWD(dR, dZ)
    s = float(np.median(np.abs(clean)))
    ref = None
    ok_pos, ok_amp = True, True
    for g in (1e-3, 1.0, 7.5, 1e4):
        x, amp, *_ = invert.invert_sample(FWD, FWD_MANY, g * clean, sq, s,
                                          x0=np.array([0.0, 0.0]))
        if ref is None:
            ref, amp0 = x, amp / g      # unit-gain reference
        ok_pos &= np.linalg.norm(x - ref) < 1e-9
        ok_amp &= abs(amp / (g * amp0) - 1.0) < 1e-9
    _report("T5 position invariant under signal scaling", ok_pos,
            "identical to < 1 nm across 7 decades of gain")
    _report("T5 amplitude scales linearly", ok_amp, "exact to 1e-9")


def t6_trajectory(seed=3, noise=0.01):
    """End-to-end on a manufactured trajectory containing a fast excursion.

    The exhaustive grid search is compared against a descent seeded from the
    true trajectory. They agree only if the grid search reached the same
    minimum a perfectly seeded descent would.
    """
    print("\nT6  trajectory tracking, warm start vs cold restart")
    rng = np.random.default_rng(seed)
    T = 240
    t = np.linspace(0.30, 0.42, T)
    tt = np.linspace(0, 1, T)
    dR = 0.05 * np.sin(2 * np.pi * 3 * tt) + 0.09 * np.exp(-((tt - 0.62) / 0.02) ** 2)
    dZ = 0.03 * np.cos(2 * np.pi * 2 * tt) - 0.06 * np.exp(-((tt - 0.63) / 0.02) ** 2)
    ip = 3e4 * np.clip(np.sin(np.pi * tt), 0, None) + 1.0

    B = np.array([FWD(a, b) for a, b in zip(dR, dZ)])
    s = float(np.median(np.abs(B)))
    B = B + rng.normal(0.0, noise * s, B.shape)

    warm = invert.invert_shot(FWD, FWD_MANY, t, ip, B, step=0.002)
    cold = invert.invert_shot(FWD, FWD_MANY, t, ip, B, search="phi",
                              phi_xy=np.column_stack([dR, dZ]))

    ew = 1e3 * np.hypot(warm["dR_m"] - dR, warm["dZ_m"] - dZ)
    ec = 1e3 * np.hypot(cold["dR_m"] - dR, cold["dZ_m"] - dZ)
    gap = 1e3 * np.nanmax(np.hypot(warm["dR_m"] - cold["dR_m"],
                                   warm["dZ_m"] - cold["dZ_m"]))

    print(f"    grid search  : median {np.nanmedian(ew):.2f} mm, "
          f"p95 {np.nanpercentile(ew, 95):.2f} mm, max {np.nanmax(ew):.2f} mm")
    print(f"    phi-seeded   : median {np.nanmedian(ec):.2f} mm, "
          f"p95 {np.nanpercentile(ec, 95):.2f} mm, max {np.nanmax(ec):.2f} mm")
    print(f"    grid vs phi  : max separation {gap:.3f} mm")
    print(f"    solver cost  : {warm['nfev'].sum()} vs {cold['nfev'].sum()} "
          f"function evaluations ({cold['nfev'].sum() / max(warm['nfev'].sum(), 1):.0f}x)")

    _report("T6 tracking error at 1% injected noise", np.nanmedian(ew) < 5.0,
            f"median {np.nanmedian(ew):.2f} mm")
    _report("T6 grid and seeded descent agree", gap < 1.0,
            f"max separation {gap:.3f} mm across the fast excursion")

    # The peak excursion is the sample most likely to reveal drift.
    k = int(np.argmax(np.abs(dR)))
    _report("T6 fast excursion tracked", ew[k] < 5.0,
            f"error {ew[k]:.2f} mm at the {1e3 * dR[k]:.0f} mm peak")


def t7_degradation(seed=4):
    """Behaviour on a dead probe, NaNs, the Ip gate and a probe subset. Each
    case must fail in its documented way rather than silently return a number.
    """
    print("\nT7  degradation and plumbing")
    rng = np.random.default_rng(seed)
    T = 60
    t = np.linspace(0.3, 0.36, T)
    dR = np.full(T, 0.04)
    dZ = np.full(T, -0.02)
    B = np.array([FWD(a, b) for a, b in zip(dR, dZ)])
    s = float(np.median(np.abs(B)))
    B = B + rng.normal(0.0, 0.01 * s, B.shape)
    ip = np.concatenate([np.full(10, 1.0), np.full(T - 10, 3e4)])

    # Ip gate
    r = invert.invert_shot(FWD, FWD_MANY, t, ip, B, ip_min=1e3, step=0.004)
    _report("T7 Ip gate", r["gated"].sum() == 10
            and np.all(np.isnan(r["dR_m"][:10]))
            and np.all(np.isfinite(r["dR_m"][10:])),
            f"{int(r['gated'].sum())} samples gated, NaN not a fitted value")

    # A NaN sample passes through as NaN without affecting its successors.
    Bn = B.copy()
    Bn[30, 4] = np.nan
    r = invert.invert_shot(FWD, FWD_MANY, t, ip, Bn, step=0.004)
    _report("T7 NaN sample isolated", np.isnan(r["dR_m"][30])
            and np.isfinite(r["dR_m"][31]),
            "NaN in, NaN out, next sample unaffected")

    # A probe at zero weight must be ignored exactly.
    Bd = B.copy()
    Bd[:, 6] = 50.0 * s
    w = np.ones(12)
    w[6] = 0.0
    rd = invert.invert_shot(FWD, FWD_MANY, t, ip, Bd, weights=w, step=0.004)
    rg = invert.invert_shot(FWD, FWD_MANY, t, ip, B, weights=w, step=0.004)
    gap = 1e3 * np.nanmax(np.abs(rd["dR_m"] - rg["dR_m"]))
    _report("T7 zero-weight probe ignored", gap < 1e-6,
            f"a 50x garbage probe at w=0 moves dR by {gap:.2e} mm")

    # Probe subsets are 1-based; an out-of-range number must raise.
    r4 = invert.invert_shot(FWD, FWD_MANY, t, ip, B, probes=[3, 4, 9, 10], step=0.004)
    ok4 = np.isfinite(r4["dR_m"][10:]).all()
    try:
        invert.invert_shot(FWD, FWD_MANY, t, ip, B, probes=[3, 99], step=0.004)
        raised = False
    except IndexError:
        raised = True
    _report("T7 probe subset", ok4 and raised,
            "4-probe run solves; out-of-range probe raises IndexError")

    # A garbage sample must return a value with a large residual.
    Bb = B.copy()
    Bb[20] = rng.normal(0.0, s, 12)
    rb = invert.invert_shot(FWD, FWD_MANY, t, ip, Bb, step=0.004)
    _report("T7 bad fit reported, not dropped",
            np.isfinite(rb["dR_m"][20]) and rb["resid_norm"][20] > 0.1,
            f"garbage sample returns a value with resid_norm "
            f"{rb['resid_norm'][20]:.2f}")


if __name__ == "__main__":
    print(f"geometry: {GEOM.source}  R0={GEOM.R0} m  P={GEOM.probe_radius} m")
    t1_on_axis()
    t2_maxwell()
    t3_symmetry()
    t4_noise_budget()
    t5_amplitude_invariance()
    t6_trajectory()
    t7_degradation()
    n_fail = sum(1 for _, ok in _results if not ok)
    print("\n" + "=" * 62)
    print(f"{len(_results) - n_fail}/{len(_results)} passed")
    for name, ok in _results:
        if not ok:
            print(f"  FAILED: {name}")
    raise SystemExit(1 if n_fail else 0)
